config:
  paths:
    data_path: /Users/ab/Data/stock_data/
  data_subfolders: 
    symbol_info: info
  screeners:
    ha: Heikin Ashi
    st: Supertrend
    srsi: Stochastic RSI
    macd: MACD
    sma1: SMA 5/10 Crossover
    sma2: SMA 10/20 Crossover
    sma3: SMA 20/50 Crossover
    sma4: SMA 20/100 Crossover
    sma5: SMA 30/100 Crossover
    sma6: SMA 50/100 Crossover
    sma7: SMA 50/200 Crossover
    sma8: SMA 100/200 Crossover
  indicators:
    ha: Heikin Ash
    st: Suptertrend
    srsi: Stochastic RSI
    macd: MACD
    sma: SMA 20/50 Crossover
  lines:
    sma20: 20 Period SMA
    sma50: 50 Period SMA
    sma100: 100 Period SMA
    sma200: 200 Period SMA
    ema20: 20 Period EMA
    ema50: 50 Period EMA
    ema100: 100 Period EMA
    ema200: 200 Period EMA